server:
  port: 8002


swagger:
  base-package: com.study
  globalOperationParameters:
    - name: "Authorization"
      description: "鉴权参数"
      parameterType: "header"
      modelRef: "string"
      #      required: "true"
      required: "false"

    - name: "x-tenant-id"
      description: "租户参数"
      parameterType: "header"
      modelRef: "string"
      #      required: "true"
      required: "false"
#  authorization:
#    name: Authorization


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    default-property-inclusion: non_null
    timeZone: 'GMT+8'
    locale: 'zh'
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



logging:
  path: 'logs/'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(${LOG_LEVEL_PATTERN:-%5p}) %boldMagenta(${PID:- }) %cyan(---){faint} %green([%thread]) %cyan(%logger{69}) %highlight([%method] [%L]) %cyan(:) %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  file:
    max-history: 3
    max-size: 50MB