server:
  port: 8002


swagger:
  base-package: com.study
  globalOperationParameters:
    - name: "Authorization"
      description: "鉴权参数"
      parameterType: "header"
      modelRef: "string"
      required: "true"

    - name: "x-tenant-id"
      description: "租户参数"
      parameterType: "header"
      modelRef: "string"
      required: "true"


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always