server:
  port: 8002


swagger:
  base-package: com.study
  globalOperationParameters:
    - name: "Authorization"
      description: "鉴权参数"
      parameterType: "header"
      modelRef: "string"
      #      required: "true"
      required: "false"

    - name: "x-tenant-id"
      description: "租户参数"
      parameterType: "header"
      modelRef: "string"
      #      required: "true"
      required: "false"
#  authorization:
#    name: Authorization


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    default-property-inclusion: non_null
    timeZone: 'GMT+8'
    locale: 'zh'
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



logging:
  path: 'logs/'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}) %boldMagenta(${PID:- }) %cyan(---){faint} %green([%thread]) %cyan(%logger{69}) %clr([%method] [%L]) %cyan(:) %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
    file: '${logging.pattern.console}'
  file:
    max-history: 3
    max-size: 50MB
  level:
    root: debug
    com:
      netflix:
        config: error
        discovery: error
        util: error
    springfox:
      bean: info
      documentation: info
    org:
      springframework: info
      apache: info
      hibernate: info
    sun:
      rmi: info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone:  http://127.0.0.1:9003/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10